version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9  # Imagen de Python para el job
      - image: redis:alpine  # Servicio de Redis (si es necesario)
        name: redis

    steps:
      - checkout  # Obtener el c칩digo fuente
      - setup_remote_docker  # Configuraci칩n de Docker remoto

      # Instalar dependencias
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest

      # Instalar Snyk CLI
      - run:
          name: Instalar Snyk
          command: |
            curl -sL https://aka.ms/install-snyk | bash
            sudo ln -s /root/.npm-global/bin/snyk /usr/local/bin/snyk

      # Ejecutar an치lisis con Snyk
      - run:
          name: Ejecutar an치lisis de Snyk
          command: |
            snyk test

      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          command: |
            . venv/bin/activate
            pytest tests/ --junitxml=test-results/junit.xml --cov=. --cov-report=html:test-results/coverage-html

      # Guardar artefactos de tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-reports

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Construir imagen Docker
          command: |
            docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$CIRCLE_SHA1 .

      - run:
          name: Login a Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Push imagen a Docker Hub
          command: |
            docker push $DOCKERHUB_USER/$IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
